export const ADD = 'todos/ADD'
export const DELETE = 'todos/DELETE'
export const SEARCH = 'todos/SEARCH'
export const LOAD = 'todos/LOAD'
export const LOAD_ERROR = 'todos/LOAD_ERROR'
export const LOAD_SUCCESS = 'todos/LOAD_SUCCESS'
